name: Deploy to Server on Push

on:
  push:
    branches:
      - master  # or your deployment branch

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Pull latest code on server
      run: |
        ssh -i /home/jimmy/.ssh/id_rsa_github root@ssh.pianolang.com "cd /root/pianolang_frontend && git pull origin master && NODE_OPTIONS=--openssl-legacy-provider npm run build && cp -r build/* /pianolang/"
